alias ls='ls --color=always -a'
alias dir='dir --color=always'
alias vdir='vdir --color=always'
alias vim='vim'
alias vi='vim'
alias espc='vim ~/.config/espanso'
alias esp='cd ~/.config/espanso'
alias qauth='mwinit -o && kinit'

alias temps='watch -n 1 sensors'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias 'gc'='git commit'
alias 'ga'='git add'
alias 'gl'='git log --all --graph'
alias 'push'='git push'
alias 'pull'='git pull'
alias 'gs'='git status'
alias 'gch'='git checkout'
alias 'gd'='git diff'
alias 'gr'='git reset'
